In [ ]:
# Chequeo del primer archivo
import pandas as pd

ruta_archivo = '../data/raw/games.csv'

df = pd.read_csv(ruta_archivo)
df #Nos muestra la tabla con todos los juegos existentes de RE

# Rectificamos que no hay valores nulos en Juegos
print("Valores nulos en Juegos: ")
print(df.isnull().sum())

Valores nulos en Juegos:
id                  0
title               0
year                0
type                0
chronology_order    0
dtype: int64

In [3]:
import pandas as pd

ruta_archivo = '../data/raw/interactions.csv'

df = pd.read_csv(ruta_archivo)
df

     game_id scene_id  character_id
0         re    re_01            16
1         re    re_01             6
2         re    re_01            15
3         re    re_02            16
4         re    re_02            17
...      ...      ...           ...
1532     re9  re9_643            80
1533     re9  re9_644            80
1534     re9  re9_644             1
1535     re9  re9_645            80
1536     re9  re9_646            80

[1537 rows x 3 columns]

In [ ]:
#EJEMPLO DE LIMPIEZA Y TRANSFORMACIÓN

# Aquí voy a desnormalizar las tablas gameAppearance, Characters y games

# Al llamar la tabla completa algunas series se repiten: character id con id_x, game_title con title, role_x con role_y, game_id con id_y por lo que se implementará un método Drop para limpiar las series del DataFrame

import pandas as pd

ruta_games = '../data/raw/games.csv'
ruta_gameAppear = '../data/raw/gameAppearance.csv'
ruta_char = '../data/raw/characters.csv'

df_gameAppear = pd.read_csv(ruta_gameAppear)
df_games = pd.read_csv(ruta_games)
df_char = pd.read_csv(ruta_char)


df_union1 = pd.merge(
    df_gameAppear,
    df_char,
    left_on='character_id',
    right_on='id',
    how='left'
)

df_union_completa = pd.merge(
    df_union1,
    df_games,
    left_on='game_id',
    right_on='id',
    how='left'
)

df_union_completa #Nos muestra la tabla inicial sin cambios

columnas_a_borrar = ['id_x','id_y','role_y','title','name'] # Define la lista de las series a eliminar
df_limpio = df_union_completa.drop(columns=columnas_a_borrar) #Define la función con el método drop

# Así podemos remplazar los nombres de una serie
df_limpio = df_limpio.rename(columns={
    'name_x': 'character_name',
    'role_x': 'role_in_game'
})

df_limpio #Ahora tenemos las tres tablas desnormalizadas; en esta tabla podemos ver todos los personajes (Principales y no princiaples) y las apariciones que tienen en los juegos originales y su cronología

,game_id,character_id,role_in_game,game_title,character_name,year,type,chronology_order
0,re,6,villain,Resident Evil,Albert Wesker,1996,mainline,2
1,re,15,hero,Resident Evil,Chris Redfield,1996,mainline,2
2,re,16,hero,Resident Evil,Jill Valentine,1996,mainline,2
3,re,17,support,Resident Evil,Barry Burton,1996,mainline,2
4,re,18,support,Resident Evil,Brad Vickers,1996,mainline,2
...,...,...,...,...,...,...,...,...
110,re_ve,25,hero,Resident Evil: Code – Veronica,Claire Redfield,2000,mainline,5
111,re_ve,38,hero,Resident Evil: Code – Veronica,Steve Burnside,2000,mainline,5
112,re_ve,39,villain,Resident Evil: Code – Veronica,Alexia Ashford,2000,mainline,5
113,re_ve,40,villain,Resident Evil: Code – Veronica,Alfred Ashford,2000,mainline,5
114,re_ve,41,support,Resident Evil: Code – Veronica,Rodrigo Juan Raval,2000,mainline,5

In [6]:
import pandas as pd

ruta_archivo = '../data/raw/gameAppearance.csv'

df = pd.read_csv(ruta_archivo)
df

,game_id,character_id,role,game_title,character_name
0,re,6,villain,Resident Evil,Albert Wesker
1,re,15,hero,Resident Evil,Chris Redfield
2,re,16,hero,Resident Evil,Jill Valentine
3,re,17,support,Resident Evil,Barry Burton
4,re,18,support,Resident Evil,Brad Vickers
...,...,...,...,...,...
110,re_ve,25,hero,Resident Evil: Code – Veronica,Claire Redfield
111,re_ve,38,hero,Resident Evil: Code – Veronica,Steve Burnside
112,re_ve,39,villain,Resident Evil: Code – Veronica,Alexia Ashford
113,re_ve,40,villain,Resident Evil: Code – Veronica,Alfred Ashford
114,re_ve,41,support,Resident Evil: Code – Veronica,Rodrigo Juan Raval

In [7]:
import pandas as pd

ruta_archivo = '../data/raw/scenes.csv'

df = pd.read_csv(ruta_archivo)
df

,game_id,scene_id,title,source
0,re,re_01,Opening FMV,https://gamefaqs.gamespot.com/ps/198462-reside...
1,re,re_02,Inside The Mansion,https://gamefaqs.gamespot.com/ps/198462-reside...
2,re,re_03,The Dining Room,https://gamefaqs.gamespot.com/ps/198462-reside...
3,re,re_04,Mysterious Puddle,https://gamefaqs.gamespot.com/ps/198462-reside...
4,re,re_05,Researcher's Will Event (Note: This scene will...,https://gamefaqs.gamespot.com/ps/198462-reside...
...,...,...,...,...
1568,re9,re9_642,The platform in the center is about to collapse.,https://game-scripts-wiki.blogspot.com/2026/03...
1569,re9,re9_643,Zeno pulls the axe from his neck. Leon prepare...,https://game-scripts-wiki.blogspot.com/2026/03...
1570,re9,re9_644,"Zeno lands numerous blows on Leon, breaking ri...",https://game-scripts-wiki.blogspot.com/2026/03...
1571,re9,re9_645,Zeno draws his revolver.,https://game-scripts-wiki.blogspot.com/2026/03...
1572,re9,re9_646,"He shoots Leon in the head, blowing it to piec...",https://game-scripts-wiki.blogspot.com/2026/03...

In [8]:
#Chequeo del segundo archivo
import pandas as pd

ruta_archivo = '../data/raw/characters.csv'

df = pd.read_csv(ruta_archivo)
df

# Rectificar si no hay valores nulos en personajes
print("Valores nules en Personajes: ")
print(df.isnull().sum())

Valores nules en Personajes:
id      0
name    0
role    0
dtype: int64