In [ ]:
# Chequeo del primer archivo
import pandas as pd

ruta_archivo = '../data/raw/games.csv'

df = pd.read_csv(ruta_archivo)
df

,id,title,year,type,chronology_order
0,re,Resident Evil,1996,mainline,2
1,re2,Resident Evil 2,1998,mainline,4
2,re3,Resident Evil 3: Nemesis,1999,mainline,3
3,re_ve,Resident Evil: Code – Veronica,2000,mainline,5
4,re0,Resident Evil 0,2002,mainline,1
5,re4,Resident Evil 4,2005,mainline,6
6,re5,Resident Evil 5,2009,mainline,8
7,re_re,Resident Evil: Revelations,2012,spinoff,7
8,re6,Resident Evil 6,2012,mainline,10
9,re_re2,Resident Evil: Revelations 2,2015,spinoff,9
10,re7,Resident Evil 7: Biohazard,2017,mainline,11
11,re8,Resident Evil Village,2021,mainline,12
12,re_sr,Resident Evil Village – Shadow of Rose,2022,spinoff,13
13,re9,Resident Evil Requiem,2026,mainline,14

In [ ]:
#Chequeo del segundo archivo
import pandas as pd

ruta_archivo = '../data/raw/characters.csv'

df = pd.read_csv(ruta_archivo)
df

    id                name     role
0    1  Leon Scott Kennedy     hero
1    2       Ashley Graham     hero
2    3            Ada Wong     hero
3    4     Ingrid Hunnigan     hero
4    5           Luis Sera     hero
..  ..                 ...      ...
78  79    Donna Beneviento  villain
79  80      Grace Ashcroft     hero
80  81       Victor Gideon  villain
81  82      Nathan Dempsey  support
82  83     Alyssa Ashcroft  support

[83 rows x 3 columns]